### ISSUE TITLE
How to record conversations

### ISSUE THREAD

**Issue by arcontechnologies** [RasaHQ/rasa-demo#100]
is there any easy way to record conversation so that they can be reused for better training ?

**Comment by akelad** [comment]
This is something we're doing with this very bot, with our Rasa Platform: https://rasa.com/products/rasa-platform/

**Comment by arcontechnologies** [comment]
fair enough. I'll consider this when I'll get my first client with Rasa as it is paid version. Meanwhile, I'll contact the sales guys to understand the model.

**Comment by akelad** [comment]
Great 🙂 I'll close this issue then
