### ISSUE TITLE
build howtogetstarted 

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#103]
many people ask where they should start learning/ reading
http://rasa.com/docs/getting-started/overview/

**Comment by akelad** [comment]
"What can you do with the Rasa Stack"

**Comment by akelad** [comment]
next step: design how the flow should look here

**Comment by LS1707** [comment]
@amn41 you unassigned us - does that mean that you also design the flow of this skill?

**Comment by amn41** [comment]
in general I think it's better to have one person assigned to an issue to coordinate. but if you have suggestions on the flow that would be great!

**Comment by LS1707** [comment]
ok perfect - thank you
