### ISSUE TITLE
Url of the webchat

### ISSUE THREAD

**Issue by frankbass3** [RasaHQ/rasa-demo#104]
Connecting to http://localhost:5001/  
i recive {"status":"ok"} 
how do i can send messages using the web interface ?

**Comment by akelad** [comment]
There's instructions on how to use the web UI here: https://github.com/mrbot-ai/rasa-webchat

**Comment by frankbass3** [comment]
Sorry i don't want make a user Interface i just would like to send a REST request for communicate with the bot i try by doing   http://localhost:5001/parse?q=hello   but  didn't work   ... what is the correct way ?

**Comment by akelad** [comment]
which rasa_core version are you using?

**Comment by frankbass3** [comment]
how do i check the rasa core version? 

python -m rasa_core.run --enable_api -d .\models\dialogue -u .\models\nlu\current  -o out.log
usage: run.py [-h] -d CORE [-u NLU] [-p PORT] [-o LOG_FILE]
              [--credentials CREDENTIALS] [--endpoints ENDPOINTS]
              [-c {facebook,slack,telegram,mattermost,cmdline,twilio}]
              [--debug] [-v]
run.py: error: unrecognized arguments: --enable_api

**Comment by akelad** [comment]
Ok looks like you've got an older rasa_core version, but are looking at the docs of 0.11. This repo isn't updated to 0.11 yet, so please look at the docs for 0.10.4: http://rasa.com/docs/core/0.10.4/
