### ISSUE TITLE
ActionSubscribeNewsletter

### ISSUE THREAD

**Issue by frankbass3** [RasaHQ/rasa-demo#105]
i download the code, i made 

•	python -m rasa_nlu.train -c nlu_tensorflow.yml --fixed_model_name current --data data/nlu/ -o models --project nlu --verbose

•	python demo/train_core.py   

which says:

ValueError: Action 'demo.actions.ActionSubscribeNewsletter' doesn't correspond to a template / action. Remember to prefix actions that should utter a template with `utter_`. Error: No module named 'demo'

**Comment by akelad** [comment]
Have you followed the installation instructions? https://github.com/RasaHQ/rasa-demo#-installation--running-of-the-bot

**Comment by frankbass3** [comment]
pip install -e .

**Comment by jwjuven** [comment]
I can't find the nlu config file " nlu_tensorflow.yml".

**Comment by akelad** [comment]
the instructions aren't updated to rasa 1.0 yet, this is something i'll do this week
