### ISSUE TITLE
Having trouble with webchat widget

### ISSUE THREAD

**Issue by arcontechnologies** [RasaHQ/rasa-demo#133]
when trying to run my run_bot.py, I'm geeting this error

```
(base) C:\Users\Albel\Documents\demobotdc>python bot.py
Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    from rasa_addons.webchat import WebChatInput, SocketInputChannel
ModuleNotFoundError: No module named 'rasa_addons.webchat'
```

```
I found out that rasa-ddons folks deprecated the connector

[Web chat channel (DEPRECATED)
***DEPRECATED - Use Rasa Core native `SocketIOChannel instead ***

from rasa_addons.webchat import WebChatInput, SocketInputChannel

agent = Agent.load(...)
input_channel = WebChatInput(static_assets_path=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'static'))
agent.handle_channel(SocketInputChannel(5500, "/bot", input_channel))]
```

I'm not familiar with SocketIOChannel, can you please advise ?

Thanks in advance.

**Comment by akelad** [comment]
That's my bad, I should've updated the docs. Please read more about it here: https://rasa.com/docs/core/connectors/#socketio-setup

**Comment by arcontechnologies** [comment]
@akelad Thanks.
There is something wrong in the doc. It stated :
```
# set serve_forever=False if you want to keep the server running
    s = agent.handle_channels([input_channel], 5004, serve_forever=False)
```
should be **"True"** instead otherwise it doesn't keep the server running.

**Comment by tmbo** [comment]
yes, the comment is wrong, should be `serve_forever=True`.

**Comment by akelad** [comment]
@arcontechnologies we'd be happy to accept a PR for the correction of this!

**Comment by arcontechnologies** [comment]
@akelad. I tried to Pull a Request (I'm not a developer) but it seems that I have to follow certain rules. if you have some guidance it will be helpfull as this is the first time I'm trying to do it.

Thanks

**Comment by akelad** [comment]
hm what rules do you mean? You should just be able to create a PR from your own fork of the repository

**Comment by arcontechnologies** [comment]
PR pulled

**Comment by akelad** [comment]
thanks, i'll close this issue now
