### ISSUE TITLE
input anything the system reply Segmentation fault

### ISSUE THREAD

**Issue by wanbiguizhao** [RasaHQ/rasa-demo#134]
python 3.5  virtualenv
os ubuntu 16.4 
i have finished all necessary  work in the readme ，
make train-core
docker run -p 8000:8000 rasa/duckling
make run-cmdline
if i input nothing just enter ，the system reploy：
![image](https://user-images.githubusercontent.com/4143246/46913392-9710da00-cfbe-11e8-93af-e7520a8ddc75.png)
if i input any words like bye，get  Segmentation fault

![default](https://user-images.githubusercontent.com/4143246/46913450-c2e08f80-cfbf-11e8-99c5-20c50f95f2a4.PNG)

**Comment by akelad** [comment]
how much memory does your machine have? it's usually something to do with that

**Comment by wanbiguizhao** [comment]
![2018-10-15 20-04-43](https://user-images.githubusercontent.com/4143246/46949922-9b6bee80-d0b5-11e8-87c0-f3df607830cc.png)
32GB Memery and 8 core

**Comment by wanbiguizhao** [comment]
thank you

**Comment by akelad** [comment]
Have you managed to resolve it?

**Comment by wanbiguizhao** [comment]
1 reboot the machine。
2reinstall the  Chinese language。
3 reset the LC_ALL 。
4retrain the nlu  and core  。
after all the action，it is working

**Comment by akelad** [comment]
computers 😅 well, i'll close this now

**Comment by wanbiguizhao** [comment]
yeah,thank you
