### ISSUE TITLE
Help to predict unknown entity value

### ISSUE THREAD

**Issue by ATS-Official** [RasaHQ/rasa-demo#135]
I am working on similar bot that captures user email and add to subscription. but in the demo code stories were written for specific email id. But in real time we may not know the email ids of new users who would like to subscribe. Could you please help how new user ids to be categorized as intent that bot can understand

enter_data{"company": "Allianz"}
action_store_company
slot{"company_name": "Allianz"}
utter_ask_businessmail
enter_data{"email": "**maxmeier@firma.de**"} OR enter_data{"number":"1"}

**Comment by akelad** [comment]
the value of the entity in the stories doesn't matter, it's just a place holder that means the entity is present. So you could write anything you want in there, like `enter_data{"email":"test"}`
