### ISSUE TITLE
Why the story files has a lot of duplicates？Do this make it train well?

### ISSUE THREAD

**Issue by winstarwang** [RasaHQ/rasa-demo#138]

**Comment by akelad** [comment]
Hey @winstarwang, they're actually not duplicates. You can probably see that all the story files have different names, like `handoff`, or `chitchat`. These repetitions of stories there all have interjections with things like `human_handoff` or `ask_weather` at different points, to be able to handle this kind of behaviour at every point of the conversation. Does that make sense?

**Comment by winstarwang** [comment]
Thanks. Maybe I didn't make my question clearly. 
In the file rasa-demo/data/core/canthelp.md, I really see the same content like this:

## just newsletter (with email already) + confirm
* greet
    - utter_greet
    - utter_inform_privacypolicy
    - utter_ask_goal
* canthelp
    - utter_canthelp

## just newsletter (with email already) + confirm
* greet
    - utter_greet
    - utter_inform_privacypolicy
    - utter_ask_goal
* canthelp
    - utter_canthelp

**Comment by akelad** [comment]
ah that's just a mistake then 😄 rasa_core deduplicates stories when training, so this has no effect on the model whatsoever

**Comment by winstarwang** [comment]
Thanks for your answers.
