### ISSUE TITLE
Add follow up stories for pipeline recommendation denied

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-demo#141]
**Problem**:

Given a story path like this:
```md
* how_to_get_started{"product": "nlu"}
  - ...
* nlu_info{"nlu_part": "entity recognition"}
  - ...
* deny
  - utter_anything_else
```
If the user then wants information on another topic (e.g. "intent classification"), the bot fails.
This is also for the other way round (nlu_info on intent classification --> deny --> info on something else).

**Proposed Solution**:
More Stories!

**Comment by akelad** [comment]
@wochinge can you give me a specific example of this? because i tried it out earlier and it worked for the things i tried i think

**Comment by wochinge** [comment]
```md
## Generated Story -8649173098350163519
* greet
    - utter_greet
    - utter_inform_privacypolicy
    - utter_ask_goal
* how_to_get_started{"product": "nlu"}
    - slot{"product": "nlu"}
    - utter_ask_for_nlu_specifics
* nlu_info{"nlu_part": "entity recognition"}
    - slot{"nlu_part": "entity recognition"}
    - utter_nlu_entity_tutorial
    - utter_offer_recommendation
* deny
    - utter_great
    - utter_anything_else
* nlu_info{"nlu_part": "intent recognition"} <-- it does not detect this one (instead it makes a fallback)
    - slot{"nlu_part": "intent recognition"}
    - utter_nlu_intent_tutorial
    - utter_offer_recommendation
```

**Comment by akelad** [comment]
i think that might be an NLU problem, rather than a core problem

**Comment by wochinge** [comment]
I don't think so. I directly passed the intents using `/greet`etc

**Comment by akelad** [comment]
so i'm gonna close this for now, do let me know if you encounter something else though

**Comment by wochinge** [comment]
ok, weird
