### ISSUE TITLE
more training data for NLU part entities

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#151]
doesn't even extract intent classification when it's misspelled 

https://website-demo.rasa.com/conversations/fb6a8a841a534925a129894ee11a6485

**Comment by akelad** [comment]
@LS1707 did we not already address this?

**Comment by LS1707** [comment]
no, we started labeling a few but not much yet

**Comment by akelad** [comment]
ok not sure where else this is going wrong because i just went through a few things and it seems to recognise it relatively well

**Comment by LS1707** [comment]
hm i saw quite some cases where it had problems when there was only one spelling mistake - I can label some stuff when the platform is back to normal

**Comment by akelad** [comment]
i mean, feel free to label it now, the platform is as normal as it's gonna get :P
