### ISSUE TITLE
idea: set the right expectations for demo bot users

### ISSUE THREAD

**Issue by alexweidauer** [RasaHQ/rasa-demo#154]
I noticed that since we have the demo bot on all docs pages, we don't indicate to the user that it is still an alpha and work in progress (we have a sentence about that on the https://rasa.com/docs/demobot/) - I wonder what would be a quick way for us to set the right expectation without too much of text.

One idea would be to add "I'm currently in development" to the greeting or something like that.

What do you think?

**Comment by LS1707** [comment]
yes, good idea - we tried that at the beginning but had too much text

**Comment by alexweidauer** [comment]
Alternatively, we could also add "Beta"/"Alpha" to the purple top bar: 

<img width="379" alt="screenshot 2018-11-19 at 07 34 59" src="https://user-images.githubusercontent.com/5676505/48690168-b5758100-ebcd-11e8-8db2-8b83a262f3e1.png">

**Comment by akelad** [comment]
The purple top bar will have the bots name (Sara), we can also add a subheading that says "I'm still in development!"

**Comment by alexweidauer** [comment]
Sounds like a good idea! Maybe even just "Sara (beta)" or so - less text to be distracted :)

**Comment by LS1707** [comment]
![image](https://user-images.githubusercontent.com/15569839/48782253-19876a80-ecde-11e8-8bb3-495b170bd786.png)
