### ISSUE TITLE
answer for -nlu or stack? -yes 

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#155]
https://website-demo.rasa.com/conversations/045a4307a900416687b5332937bfdcd8/1542302631.1485403

maybe create a response for if they just say yes?

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/91eece3b16a94a5191879fda19149bec/1542302233.208968 hm but here it worked

**Comment by akelad** [comment]
both NLU problems and fixed
