### ISSUE TITLE
Bot offers information on "components of Rasa" but doesn't understand that query

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa-demo#156]
![image](https://user-images.githubusercontent.com/20581300/48669856-433d6780-eb0d-11e8-96c4-e772b8142cac.png)
===============
or

![image](https://user-images.githubusercontent.com/20581300/48669858-4f292980-eb0d-11e8-8848-2ca70f0f51a8.png)

**Comment by Ghostvv** [comment]
+1 didn't understand `what are the components?`

**Comment by akelad** [comment]
fixed by adding training data
