### ISSUE TITLE
mood affirm after utter_anything_else answers thumbs up

### ISSUE THREAD

**Issue by DominikRos** [RasaHQ/rasa-demo#169]
https://website-demo.rasa.com/conversations/dominik/1542626826.3874798

<img width="1395" alt="screen shot 2018-11-19 at 12 29 26" src="https://user-images.githubusercontent.com/31856927/48704427-c7b7e500-ebf6-11e8-9a68-0cd130232a7b.png">

**Comment by akelad** [comment]
covered by #194
