### ISSUE TITLE
Asking twice for the builder does not work

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa-demo#175]
http://website-demo.rasa.com/conversations/d041ba4b0a89479e9bb6a5007f2cdc87/1542250104.0721016

<img width="671" alt="bildschirmfoto 2018-11-19 um 12 35 37" src="https://user-images.githubusercontent.com/1098412/48704735-a3103d00-ebf7-11e8-853a-0bf31ee4a7c0.png">

**Comment by akelad** [comment]
well, "who" is kind of ambiguous... i'd say this was handled correctly

**Comment by tmbo** [comment]
But it shouldn't trigger a fallback, that was my point (even if the person said, `so, who is that builder`)

**Comment by tmbo** [comment]
right, so yes, or `One of the smart ...` again - but you are right it is unclear if there even is a dialogue issue or if it is just because of the nlu prediction

**Comment by akelad** [comment]
yeah i think it's just nlu
