### ISSUE TITLE
Wrong nlu classifications

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa-demo#183]
- `give me a girl firend` - enter_data
- `call me father` - contact_sales
- `no job` - deny (maybe but flow does not handle this correctly)
- `money is all ok` - enter_data (but not confident enough, triggers fallback)
- `very much` - deny
- `are you a human?` - human_handoff

**Comment by akelad** [comment]
fixed all of them apart from "are you a human", which we will cover with chitchat

**Comment by tmbo** [comment]
:rocket:
