### ISSUE TITLE
Chitchat "are you learning"

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa-demo#185]
Might make sense to add something: "I am always learning and trying to get better every day"

http://website-demo.rasa.com/conversations/fef889fe911f4d0298e2a227465e4261/1542203448.6948917

<img width="661" alt="bildschirmfoto 2018-11-19 um 12 49 10" src="https://user-images.githubusercontent.com/1098412/48705483-8a088b80-ebf9-11e8-8609-866b8bbbbda6.png">

**Comment by akelad** [comment]
covered by #195
