### ISSUE TITLE
handle mood confirm after noworries

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa-demo#189]
http://website-demo.rasa.com/conversations/992de37f759643278b47ddd23ecc98ed/1541594881.0920813
<img width="667" alt="bildschirmfoto 2018-11-19 um 12 53 20" src="https://user-images.githubusercontent.com/1098412/48705714-30ed2780-ebfa-11e8-8e14-1e4da4f395a4.png">

**Comment by akelad** [comment]
gonna close because it is handled, but nlu failed. i think this could be a separate intent though, like praising the bot and him being like "I'm glad I could help" or something
