### ISSUE TITLE
chitchat collection

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#195]
what's your surname
are you an AI 
what's your work 
is a bot different from an AI

**Comment by LS1707** [comment]
what are you doing
tell me more about yourself 
how old are you

**Comment by tmbo** [comment]
Are they based on any evidence? I’d only add stuff that people asked for

**Comment by akelad** [comment]
yes they are.
one thing i think is also making the weather more contextual maybe. not sure if this is something that happens a lot but before when we had the weather as a prompt, people would start asking about the weather in india, and then a followup "what about detroit" or something

**Comment by akelad** [comment]
another thought i had this morning was chitchat questions about Sara. i suspect there might be some of those in future, since the bot now has a personality

**Comment by LS1707** [comment]
whats your role
are you human
restaurant
thankyou
facts about cats
what are you doing
what time is it
restaurant search
i was lying
which colour has an apple
user told his name
what is your address
tell me more
meaning of rasa
how do you work
how many skills do you have
how can i start investing
what is rasa core
what color do you like
romanian as language want to talk to you
technical questions
weird stuff
how old are you
restaurant
first time rasa
are u there
who am i
where are you from
what languages
book hotel
is rasa open source?
does rasa speak italian
are you made with rasa
i undesrtand how powerful rasa is
tutorial
what time is it
do you understand portuguese
chinese food
pizza places

**Comment by LS1707** [comment]
- tell me a joke
- how old are you
- what time is it 
- what languages do you speak
- insults handling 
- restaurant
- who am i/ whats my name
- how were you built
- nice to meet you 
- where are you from 

- make ask_weather more contextual? juste's weather bot?
