### ISSUE TITLE
FAQ collection

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#197]
what is the technology behind rasa
what languages do you support 
can bot be in italian
what are contextual assistants and how are they different from chatbots
how to keep rasa model loaded on server
rasa nlu tutorial
what is tensorflow
source for rasa nlu sample
what are slots / what is slot filling II 
where can i integrate my bot
how to install rasa core on my local system
simple project example
nlu support
how can I build a bot IIIII 
tell me more about rasa platform II 
tell me aout RNN

**Comment by LS1707** [comment]
send docs
what languages available
how accurate is rasa
entity extraction, how install rasa stack, who founded rasa
rasa costs
how to utter an image
how to add new language
do you use deep learning
rasa costs
need banking use case
is rasa open source
how install on cloud
error in code
need tutorial
languages
asked if ml is included
support for serbian language
what is entity
install
language support
bot examples
how do i use fasttext with spacy scikitlearn
languages
sample code
mongo DB
latest release
alexa
analytics for rasa
pipeline, install rasa
demo
how to use rasa with windows
cannot install rasa on anaconda
how to use the evaluate module from python
asked for formal documentation
how to install rasa
story
how do you interpret  as question
tutorial
error in code
technical questions, handoff
how to train
oos resources for getting started
voice possible?
can i respond with buttons
possible to integrate with fb
oos help
how to delete single slots
we want to build a sales bot
help me with django
issue with documenttation page
google
what is duckling
how does rasa work
can rasa store context of conv
django
regex
tutorial
component list
cell issues in quick start pt 3
can't run quickstart
which language is rasa
channels supported by rasa
how to connect with rasa
install rasa on linux
components of rasa
ui for rasa
how to start server
where can i get trainnig data
components of rasa
what os systems do you support
What is kind of approach i should think of when i decide how many intents i should include on my training data
questions about training data
interactive learning
fallback action
do you handle context
difference stack and only NLU
how can i download 0.13.7
unable to install on ubuntu

**Comment by akelad** [comment]
New faqs:
- what is pip
- what is conda
- tell me about the rasa architecture (?)
- what is dialogue management
- what is structured data

**Comment by akelad** [comment]
- what is your privacy policy

**Comment by akelad** [comment]
- are you better than dialogflow

**Comment by akelad** [comment]
- why are you called Sara

**Comment by akelad** [comment]
- how do you learn
- what is an intent

**Comment by wochinge** [comment]
@akelad can we close this one?

**Comment by akelad** [comment]
nah i think this is still good to have in case we decide to implement more FAQ stuff

**Comment by melindaloubser1** [comment]
@akelad we still want to keep this open?

**Comment by akelad** [comment]
nah let's close
