### ISSUE TITLE
how_to_get_started{"product":"nlu"} > utter_core_tutorial

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#199]
that happened quite often
https://website-demo.rasa.com/conversations/d75d1ac725164b3c976193eb54feb756/1542617787.2052836

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/4986d88ccb784dc19dc5a553a8e07890/1542613700.8361673 here it's the other way around

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/7830abb04e1c49809d89b0d420443928

**Comment by akelad** [comment]
fixed
