### ISSUE TITLE
jumped to sales after mood_confirm

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#200]
https://website-demo.rasa.com/conversations/29d264d8ce574a11bde572f0e79b73f3

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/6fd65c93e374489f9c8d76697ab9c493

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/35d1ecc91c364cbf8a6edf006e5d8c9a

**Comment by akelad** [comment]
fixed
