### ISSUE TITLE
implement FAQs 

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#203]
the FAQs we want to implement first:

* ask_faq_platform: what is rasa platform
* ask_faq_languages: what languages does rasa support
* ask_faq_tutorialcore/ ask_faq_tutorialnlu: tutorial for NLU and core
* ask_faq_opensource: is rasa open source
* ask_faq_voice: rasa & voice / alexa
* ask_faq_slots: what are slots
* ask_faq_channels: what channels does rasa support
* ask_faq_differencecorenlu: difference core and NLU

**Comment by EPedrotti** [comment]
@LS1707 do we have the answers to the faqs?

**Comment by akelad** [comment]
you can test it without the answers for now, those we need to add to the platform anyways rather than locally
