### ISSUE TITLE
How to handle questions like "what is rasa stack"

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#207]
or "what is rasa core"
Do we treat this as the getting started intent, or have it as an FAQ?
e.g. https://website-demo.rasa.com/conversations/d3633c3050a8415387d245267d962703/1542517911.7044106

**Comment by LS1707** [comment]
I'd say FAQ, but on the same hand I'd be worried that we make the bot an FAQ bot.

**Comment by akelad** [comment]
yeah i'm not so sure.. because it does get handled in the getting started flow eventually, but the question is do we want the user to go through a longer flow when all they wanna know is what rasa core is 😛

**Comment by LS1707** [comment]
no
