### ISSUE TITLE
skip privacy policy when user already saw that message

### ISSUE THREAD

**Issue by alexweidauer** [RasaHQ/rasa-demo#209]
I think we discussed this already - if the user has seen the privacy message once, it should not appear again even if the user _greets_ again (esp. as part of the discussion of context - in this case conversation history is easy to support)

see http://website-demo.rasa.com/conversations/e3a152f3854b4a6ea799f4116d36633c/1543142924.4357507

**Comment by akelad** [comment]
ok i'll look into fixing this, i thought it'd been fixed but clearly not for every case

**Comment by akelad** [comment]
fixed
