### ISSUE TITLE
product: nlu >>> action: core

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#213]
https://docs.google.com/spreadsheets/d/15cKBE58GUoJEptGYGk3hocwhFMiqUD1wU2HilvFhzXk/edit#gid=0 basically everything in this list from the 23rd with "core" in "if not why" had the issue that the user asked for information about NLU and we sent them a core tutorial (or the other way around). I thought we fixed that? or was that after those conversations?

**Comment by akelad** [comment]
i believe these are old conversations... all the issues in there are things i think i've fixed already. will close this for now, but please re-open/create a new issue if you see the same behaviour from the 24th onwards

**Comment by LS1707** [comment]
ok
