### ISSUE TITLE
UTF-8 in the domain.yml(text action) file generated an error during training

### ISSUE THREAD

**Issue by kenoiloan** [RasaHQ/rasa-demo#214]

**Comment by akelad** [comment]
i assume you're using python 2? this is a py3 only project

**Comment by kenoiloan** [comment]
![utf-8 file domail](https://user-images.githubusercontent.com/7262044/49053607-5d6cf900-f223-11e8-8910-7f51d4472765.png)
![pythonscreen](https://user-images.githubusercontent.com/7262044/49053639-82616c00-f223-11e8-92ce-23e1279432a3.png)

Can you show me how to put a non-english language into that file?Specifically, it is Vietnamese
