### ISSUE TITLE
second greet only be "hi"

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#216]
https://website-demo.rasa.com/conversations/9ae5c78ba2494dd4950cc0231e04b0be/1543148351.8967752

it shouldn't say two times "i'm sara"

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/d121dfda690c4ae4ad577cf2a87a5539/1543141138.1334753

could we also exclude the "I'm sara" part if the user says "hi sara"?

**Comment by akelad** [comment]
will be fixed in next release
