### ISSUE TITLE
I don't found the intent get_started_step4

### ISSUE THREAD

**Issue by LuisQ95** [RasaHQ/rasa-demo#230]
Hi, I want to send my suggestion but don't found this intent get_started_step4

![intencion](https://user-images.githubusercontent.com/40223102/49876816-22a5bc00-fdf2-11e8-8b9c-4eb30efeed2b.PNG)

**Comment by akelad** [comment]
you can post any suggestions you have here :) this is a skill that's usually deployed here https://rasa.com/docs/get_started_step4/

**Comment by LuisQ95** [comment]
I understand. Thank you!.

**Comment by akelad** [comment]
i'll close this issue then!
