### ISSUE TITLE
jumped to wrong user goal

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#243]
https://website-demo.rasa.com/conversations/15f92cc91e4e4c86826ffd023f4d1ef7/1544969157.4125402

also, I'm not sure if that's not a problem with getstarted_3 stories

**Comment by LS1707** [comment]
https://website-demo.rasa.com/conversations/67a8696eb5894b25a800b6cbd7a695bb

**Comment by akelad** [comment]
no, nothing to do with step3, it's just a general problem i think

**Comment by akelad** [comment]
github is being buggy and i can't reassign this to myself, but i'll take care of it
