### ISSUE TITLE
change utterance built bot before

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#246]
![image](https://user-images.githubusercontent.com/15569839/50083003-b6142e00-01f2-11e9-848f-617794940dfc.png)

**Comment by netcarver** [comment]
@LS1707 Linda, curious about the (web based) channel you are testing on there. It has a similar look to mrbot-ai's rasa-webchat component but your's appears to have inline nlu/tracker debug data in the dialog flow. Is that an internal Rasa tool or an open source one?

**Comment by akelad** [comment]
@netcarver this is our enterprise product: https://rasa.com/products/rasa-platform/

**Comment by netcarver** [comment]
@akelad Thanks Akela!
