### ISSUE TITLE
 Failed to connect to duckling http serve

### ISSUE THREAD

**Issue by lansedebing** [RasaHQ/rasa-demo#263]
Failed to connect to duckling http server. Make sure the duckling server is running and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /parse (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027F1B24E320>: Failed to establish a new connection:

**Comment by akelad** [comment]
Please refer to the README on how to properly run that: https://github.com/RasaHQ/rasa-demo#-how-to-install-and-run-sara

**Comment by bofengshuimen77** [comment]
I still have question. If I don't want to use docker, what should i do?

**Comment by akelad** [comment]
you can manually install it from the facebook repo, however we strongly recommend using docker

**Comment by surajhes** [comment]
I have manually installed and running the duckling server. Even then i see the same error.

**Comment by ZeweiChu** [comment]
I got the same error as well.

**Comment by anilbg189** [comment]
Am using docker but still am getting the same error.

**Comment by ankitbansal811** [comment]
Please make sure you are running a duckling server on localhost port 8000.

If you are running some other service on port 8000, then you can bind any other port with the container's port and specify that in your pipeline config.

Example: `docker run -p <Desired Port, ex- 1000>:8000 rasa/duckling`

Change config file to reflect that. Your pipeline should include
`- name: DucklingHTTPExtractor
# https://rasa.com/docs/rasa/nlu/components/#ducklinghttpextractor
  url: http://localhost:<Desired Port, 1000>`

Retrain your model with changed config. After training, simply run: rasa run

**Comment by ermarkar** [comment]
still not working, i am running it locally, and http://localhost:8000 says **quack**, 

  ```
- name: "DucklingHTTPExtractor"
    # url of the running duckling server
    url: "http://localhost:8000"
    # dimensions to extract
    dimensions: ["time"]
    # allows you to configure the locale, by default the language is
    # used
    locale: "de_DE"
    # if not set the default timezone of Duckling is going to be used
    # needed to calculate dates from relative expressions like "tomorrow"
    timezone: "Europe/Berlin"
    # Timeout for receiving response from http url of the running duckling server
    # if not set the default timeout of duckling http url is set to 3 seconds.
    timeout: 3
```

and the error

`rasa.nlu.extractors.duckling_entity_extractor  - Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by NabeelQaiser** [comment]
> still not working, i am running it locally, and http://localhost:8000 says **quack**,
> 
> ```
> - name: "DucklingHTTPExtractor"
>   # url of the running duckling server
>   url: "http://localhost:8000"
>   # dimensions to extract
>   dimensions: ["time"]
>   # allows you to configure the locale, by default the language is
>   # used
>   locale: "de_DE"
>   # if not set the default timezone of Duckling is going to be used
>   # needed to calculate dates from relative expressions like "tomorrow"
>   timezone: "Europe/Berlin"
>   # Timeout for receiving response from http url of the running duckling server
>   # if not set the default timeout of duckling http url is set to 3 seconds.
>   timeout: 3
> ```
> 
> and the error
> 
> `rasa.nlu.extractors.duckling_entity_extractor - Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Started facing the same issue since last week

**Comment by NabeelQaiser** [comment]
> > still not working, i am running it locally, and http://localhost:8000 says **quack**,
> > ```
> > - name: "DucklingHTTPExtractor"
> >   # url of the running duckling server
> >   url: "http://localhost:8000"
> >   # dimensions to extract
> >   dimensions: ["time"]
> >   # allows you to configure the locale, by default the language is
> >   # used
> >   locale: "de_DE"
> >   # if not set the default timezone of Duckling is going to be used
> >   # needed to calculate dates from relative expressions like "tomorrow"
> >   timezone: "Europe/Berlin"
> >   # Timeout for receiving response from http url of the running duckling server
> >   # if not set the default timeout of duckling http url is set to 3 seconds.
> >   timeout: 3
> > ```
> > 
> > 
> > and the error
> > `rasa.nlu.extractors.duckling_entity_extractor - Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`
> 
> Started facing the same issue since last week

It was solved by installing duckling directly on system instead of running via Docker image. Reference : https://medium.com/@adboio/using-duckling-to-extract-dates-and-times-in-your-rasa-chatbot-7687f4fde2e0
