### ISSUE TITLE
Rename spacy and tensorflow pipelines

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa-demo#264]
Pipelines have been renamed in 0.14.0a2:
`spacy_sklearn` -> `pretrained_embeddings`
`tensorflow_embedding` -> `supervised_embeddings`

This needs to be changed in the suggested pipelines.

**Comment by akelad** [comment]
@wochinge can you take care of this?

**Comment by tmbo** [comment]
does depend on https://github.com/RasaHQ/rasa_nlu/pull/1588 to be merged though, which is not finished yet.

**Comment by akelad** [comment]
ok i'm gonna unassign tobias then though, i thought this was done already

**Comment by erohmensing** [comment]
collecting this and similar issues in #298
