### ISSUE TITLE
implement elaboration/explain intent

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#266]
https://website-demo.rasa.com/conversations/f110cd4e94e74d18ad13bc3841cf1b3a/1546965189.2481441

Add
* Intent which captures the user's intention to get to know more about a topic, e.g. "Why", ~"Give me an example"~, "Tell me more", "Could you please explain that"? 
* NLU data for intent

Change:
* ~give possibility to ask for example after Core / NLU explanation~
* disambiguation after `utter_ask_which_product`
* check whether you can replace other intents with this new one such as `ask_why_contribute`
* check for other places where this could make sense (no need to implement them all asap)

Others:
* write down your feedback and experiences! :rocket:

**Comment by akelad** [comment]
issue #201 is relevant here

**Comment by akelad** [comment]
issue #117 also relevant

**Comment by akelad** [comment]
#149

**Comment by akelad** [comment]
#279 also kind of relevant

**Comment by tabergma** [comment]
We cannot replace the intent `ask_why_contribute`. The intent is used in stories like
```
## Prompt -> Contribute
* get_started_step4
    - action_greet_user
* ask_why_contribute
    - utter_reasons_to_contribute
* ask_how_contribute
    - utter_possibilities_to_contribute
```
If we would replace the intent here with `explain`, we would not know what the user wants to get explained. We could just give a generic answer.
