### ISSUE TITLE
Improve demo bot (Step 1 and 3)

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-demo#280]
Go through flagged conversations and fix stuff

**Comment by tmbo** [comment]
@imLew did you have time to look at this?

**Comment by imLew** [comment]
> @imLew did you have time to look at this?

No, couldn't really go through flagged conversations as there were some issues with models (fixed now). 
Also the goals for sara changed this was created so I don't think improving these steps is an goal any longer.

**Comment by tmbo** [comment]
Ok sounds good

**Comment by akelad** [comment]
i'm gonna close this now, because we're not doing this in the near future
