### ISSUE TITLE
Syntax errors on training core

### ISSUE THREAD

**Issue by tarabyte0101** [RasaHQ/rasa-demo#284]
self.async = None
             ^
SyntaxError: invalid syntax
make: *** [train-core] Error 1

At this point, I just want to uninstall rasa-demo. I will try again at some point in the future, but it's not going to work for my purposes right now. Could you please tell me how to cleanly uninstall it?

**Comment by akelad** [comment]
which python version are you running? I assume python 2? This only works with python 3

**Comment by tarabyte0101** [comment]
Python 3

**Comment by akelad** [comment]
but 3 what, 3.5 or 3.6?

**Comment by akelad** [comment]
Also this looks like an error from the rasa_core repo -- you should install the compatible core versions rather than the latest ones. Do you know which version you currently have installed?

**Comment by tarabyte0101** [comment]
Hi,

Apologies for not being more explicit. Below is the version I have running
of Python. As for the core, I just followed the instructions that are
listed on the Git page for the Rasa-demo to install. If you could help me
through what I need to do to install the core, that would be great.
However, I would really like to be able to cleanly uninstall everything,
and understand all the steps to cleanly install from the start as I would
like to be able to essentially write out instructions for my students.

Taras-MacBook:Documents tarabyte.0101$ which python3

/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

**Comment by akelad** [comment]
hm ok, so we don't support python 3.7 yet -- can you try installing python 3.6 instead? If the error still persists, please post the full error trace
