### ISSUE TITLE
implement a dummy handoff skill

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#292]
Add some code to handoff to a human on e.g. Slack. Again, does not necessarily need to be used on the live bot, but we should have a code example of this in the repo

**Comment by obsidienne** [comment]
Hi,

May be you can quickly explain how to do this ? Do I need to create a custom channel or do I need something else ?

Thanks

**Comment by akelad** [comment]
you would do this in a custom action, by querying your API (wherever the human handoff happens) and then returning a `ConversationPaused()` event -- that's one way you can do it

**Comment by obsidienne** [comment]
Hi, 

I have followed https://github.com/moaazsidat/rasa-handoff and the forum. And maybe I misunderstand what a human handoff is.

For me a hand off is :
- user talks to the bot
- user asks to speak to a human (with a TwoStageFallbackPolicy for example or a explicit intent)
- the bot is disconnected (event paused sent from a custom action)
- user can speak / chitchat with a human agent

But following https://github.com/moaazsidat/rasa-handoff, you can't have chitchat with human agent. Human agent can only respond, not have a conversation.

May be what I'm looking for is human-in-loop ?

Thanks for response

**Comment by akelad** [comment]
well you'd have to change that implementation then -- it shouldnt be a problem for there to be a conversation with the human agent. I'm not sure what you mean by they can only respond though

**Comment by obsidienne** [comment]
Thanks for your quick response.

> I'm not sure what you mean by they can only respond though

When I'm in the custom action querying my API for a human response, I understand

- how to return a paused event / resume event
- how to send a query to an external API (like an external chat for human agent)
- how to send to the rasa channel (discord/slack/...) the human agent response retrieved from the API 

But when paused, how rasa sends the user message to the human agent afterward ?
There is no loop or direct connection between the user and the human agent .

I'm missing something.

**Comment by akelad** [comment]
ah ok well this again depends on what kind of platform you're using for the human agent thing. Usually (at least form what i've seen) the agent can see the whole conversation that's happening anyways, and can then interfere from there either when the bot hands off itself or the agent can also directly take over the conversation by clicking a button

**Comment by darkblueorange** [comment]
Hello there, 
We have exactly the same problem than @obsidienne. 
What I understand is that you are asking us to duplicate the conversation from the front-end to both 'back ends': rasa side, and human agent supervision stuff side. 

Intuitively we would think -from a handover perspective implementation- that when rasa is "paused" it would be prevented from answering the user, but not blocked for receiving/parsing messages, and could therefore continue to forward it to human agent (with special mechanism in custom action or so).

**Comment by akelad** [comment]
but rasa is still listening, it's just not parsing/answering messages

**Comment by darkblueorange** [comment]
Ok thank you. I understand that the tracker continue to be filled then, but we are not aware anymore as there is no custom action that can be triggered while Rasa is paused.

Said differently, how can we know when RASA is receiving a new message in order to pull it and forward it to the human agent stuff ?

Or is there a way to force RASA to push conversations to a supervision stuff when paused ?

**Comment by darkblueorange** [comment]
Any luck ?
Please :)

**Comment by akelad** [comment]
The events will still be appended to the tracker, so the conversation should still get displayed. There's an endpoint in Rasa to query the tracker as well.
If you have any more questions about this, please make a post in the [forum](https://forum.rasa.com) :) that's where we usually answer usage questions

**Comment by darkblueorange** [comment]
I’m not sure I could make my point as the agent/supervisor console is only triggered by custom actions, we need some way to be aware of any messages received when RASA is paused.
Continuously polling the tracker doesn’t seem a efficient way of having a conversation displayed on the supervision console.

Anyway, thank you 
We’ll continue searching other ways

**Comment by ravikrcs** [comment]
> Add some code to handoff to a human on e.g. Slack. Again, does not necessarily need to be used on the live bot, but we should have a code example of this in the repo

could you give me some hint how to implement handoff to human on Slack.
i want to use slack where human can takeover the conversation.

**Comment by melindaloubser1** [comment]
@akelad can we close this in favour of https://github.com/RasaHQ/helpdesk-assistant/issues/17 ?
