### ISSUE TITLE
tensorflow error DataTyle float16 

### ISSUE THREAD

**Issue by lpschaub** [RasaHQ/rasa-demo#294]
Hello,

when I use the command

make train-code

I have the following error :
", ".join(dtypes.as_dtype(x).name for x in allowed_list))) TypeError: Value passed to parameter 'input' has DataType float16 not in list of allowed values: float64, float32, complex64, complex128 make: *** [train-core] Erreur 1
Any clues ?
Thanks

**Comment by akelad** [comment]
can you post the full trace? As in, where is the error coming from?

**Comment by melindaloubser1** [comment]
closing as stale
