### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by bedbodys** [RasaHQ/rasa-demo#296]
Train the NLU model to report an error:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

What Shall I doWhat Shal

**Comment by akelad** [comment]
could you provide some more details, like which python version you're using and which NLU version?

**Comment by erohmensing** [comment]
The traceback would be great to have too. This is possibly related to [this error](https://github.com/RasaHQ/rasa_core/issues/1858)

**Comment by bedbodys** [comment]
First of all, thank you for your reply; secondly, I'm sorry to reply to your question so late. The Python I use is version 3.6 and rasa_nul is 0.13.7! @akelad

**Comment by bedbodys** [comment]
I think it has something to do with the configuration of the computer environment.

**Comment by bedbodys** [comment]
The system used is WINDOWS，Can run it with Linux system

**Comment by akelad** [comment]
could you post the whole traceback please

**Comment by melindaloubser1** [comment]
closing as stale
