### ISSUE TITLE
i want to do End-to-end evaluation of Rasa NLU and Core,but it went wrong

### ISSUE THREAD

**Issue by LiuJun26** [RasaHQ/rasa-demo#297]
![image](https://user-images.githubusercontent.com/31444072/54596195-1c695080-4a6f-11e9-8e25-e5634a693cc4.png)
as shown  in the figure, i don't know how solve it......hope your can help me .thank you very much

**Comment by erohmensing** [comment]
Ah, if you're seeing policy priority, that means you're running the wrong version of rasa_core. That property is currently only on the rasa_core master branch, which is still bleeding edge, i.e. not to be used for this demo. Did you download the dependencies for this project? (I would recommend doing that in a virtual environment if you don't want to mess with your current rasa_nlu and rasa_core versions)

**Comment by LiuJun26** [comment]
1).rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.13.3 Instance version: 0.14.0a1 Minimal compatible version: 0.14.0a1
2).
![image](https://user-images.githubusercontent.com/31444072/54658647-77e81c80-4b09-11e9-84ae-2e43329e82a1.png)
3)
![image](https://user-images.githubusercontent.com/31444072/54658730-e6c57580-4b09-11e9-8c81-afe3a8961afe.png)

i might know...,very  very very thank you

**Comment by erohmensing** [comment]
> rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.13.3 Instance version: 0.14.0a1 Minimal compatible version: 0.14.0a1

This error tells you what you need to know -- even though your `pip show rasa-core` shows 0.13.3, it looks like you're running  from inside a git repository where you've cloned the latest version of rasa_core. You should retrain your model. 

If you want to run the model that you made on 0.13.3, you should make a virtual environment where you `pip install rasa-core==0.13.3` and put your `flightbot` directory (not the entire `rasa_core` directory as it comes from the master version) there.
