### ISSUE TITLE
Improve error handling during installation

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa-demo#299]
http://website-demo.rasa.com/conversations/54e7b3e656f547afb5c028465436ef0a

When a user encounters the problem of `tensorflow version 1.12.0 not found` during installation, the bot ends up in an endless loop. See example above.

To fix the problem, the bot should check the python version of the user. tensorflow 1.12.0 is compatible with python 3.6 but not with python 3.7. Thus, the bot should inform the user that he should use python 3.6 instead of python 3.7.

**Comment by melindaloubser1** [comment]
with the newer versions of rasa this no longer applies (although I'm sure there are similar issues for some users). I'm closing it but if error handling is still something we want to implement in general feel free to reopen
