### ISSUE TITLE
Rasa how to dealing with  context  problems in Several rounds of talks

### ISSUE THREAD

**Issue by LiuJun26** [RasaHQ/rasa-demo#303]
![image](https://user-images.githubusercontent.com/31444072/54900379-f1b74600-4f0d-11e9-8fc6-109d158df5f4.png)

recently I'm making a chatbot with rasa-core and pytext. but i got a problem,maybe some others people  meet -----how do  i get the context message?  how do i get what the bot says ? for example  
![image](https://user-images.githubusercontent.com/31444072/54901468-81aabf00-4f11-11e9-8ae5-00df4109b1d3.png)

rasabot say " What's your job? " ， i answer " i dont want to tell you ".     in rasa-core i can easy access what people said ,but how can i get  the corresponding question?. i know rasa-core use templates to answer quenstions,    ( my english is very poor,I wish I could be clear)

**Comment by akelad** [comment]
i'm not sure i understand what you mean? but if you're looking at that example there, then this is the relevant story:
https://github.com/RasaHQ/rasa-demo/blob/master/data/core/stories.md#anything-else---yes
