### ISSUE TITLE
restart at end of two stage fallback policy is broken

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#314]
<img width="373" alt="Screen Shot 2019-05-08 at 13 52 21" src="https://user-images.githubusercontent.com/22333512/57400184-8f9e6180-7198-11e9-9d3e-aadf25f9f41d.png">

**Comment by Pratiksha1312** [comment]
Hi!! Is this issue resolved?? I am facing the same issue in mine.. Please help me if any resolution is found out?

**Comment by akelad** [comment]
we're looking into it with the PR that's currently open, @msamogh will take care of it

**Comment by msamogh** [comment]
@erohmensing Could you share the full conversation? I wasn't able to reproduce it.

**Comment by wochinge** [comment]
@erohmensing is that still a thing?

**Comment by erohmensing** [comment]
No idea, but pretty sure it was a demobot thing and not a rasa thing, if i get time to test the demobot PR will take a look
