### ISSUE TITLE
ValueError: You have to provide a valid path to a config file.

### ISSUE THREAD

**Issue by Duanexiao** [RasaHQ/rasa-demo#323]
when i try to run the command: make train-core, the error raised that : ValueError: You have to provide a valid path to a config file. The file 'rasa-demo/policy.yml' could not be found.Any one else met that question?

**Comment by akelad** [comment]
@Duanexiao sorry the repo hasn't been properly updated yet -- it now runs with Rasa 1.0 rather than rasa-core/nlu separately. We'll make a fix soon

**Comment by Duanexiao** [comment]
@akelad   ok,many thanks.

**Comment by akelad** [comment]
once you have rasa 1.0 installed, you should just be able to run `rasa train`
