### ISSUE TITLE
tracker_store - Store type 'SQL' not found. Using InMemoryTrackerStore instead

### ISSUE THREAD

**Issue by EmannuelRoque** [RasaHQ/rasa-demo#324]
Hi,

I'm trying to enable the SQL tracker store (http://rasa.com/docs/rasa/api/tracker-stores/#sqltrackerstore).

I'm getting the message:
WARNING  rasa_core.tracker_store  - Store type 'SQL' not found. Using InMemoryTrackerStore instead

Should it works just adding this lines in the endpoint.yml file, right?

tracker_store:
    type: SQL
    dialect: "mysql+pymysql"
    url: "55.55.55.55"
    db: "chatbots_log"
    username: user
    password: pass

Thanks
Emannuel Roque

**Comment by akelad** [comment]
Which version are you using? This repo now only runs with rasa 1.0, we haven't quite fully updated all the requirements in here yet
