### ISSUE TITLE
Mimic chitchat stories with FAQ as well

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa-demo#332]
The chitchat-related stories currently cover most of the scenarios, but the FAQs are lagging behind a bit. Since both of them are essentially of the same format (you get interrupted by FAQ/chitchat - you handle it - you go back to doing what you were before), it should be possible to simple copy paste most of the stories from chitchat and replace it with FAQ intents.

**Comment by melindaloubser1** [comment]
handled by  porting faqs & chitchats to response selector
