### ISSUE TITLE
Push notifications using asynchronous custom action

### ISSUE THREAD

**Issue by sandeepparkar** [RasaHQ/rasa-demo#339]
Is there a way to execute something in the background which might take a few hours and when it's done. We can send out a push notifications on Rasa screen.
Something like your pizza is ready for pickup.

**Comment by akelad** [comment]
You can use the `ReminderScheduled` event for something like that: https://rasa.com/docs/rasa/api/events/#schedule-a-reminder

Please post questions on our [forum](https://forum.rasa.com) though

**Comment by sandeepparkar** [comment]
Thanks for this. Will try it and let you know
