### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa-demo#341]
https://rasa.com/docs/demobot/

seems broken =(

**Comment by koaning** [comment]
![image](https://user-images.githubusercontent.com/1019791/66601368-05738280-eba8-11e9-8da6-c15a1b4fbb4d.png)

**Comment by akelad** [comment]
yes it temporarily doesn't exist :( but, I can tell you it's in the plans to bring the bot back on the docs very soon!
