### ISSUE TITLE
Low Intent confidence while using rasa 1.3

### ISSUE THREAD

**Issue by MingL0L** [RasaHQ/rasa-demo#342]
I'm runing the rasa-demo on my ubuntu 18.04 VM. I did download the source code, install everything from requirement.txt, train nlu and test it using "rasa shell nlu" . Everything works well.
- For exemple, if i say "how old are u" , i got: 
  - "intent": { "name": "ask_howold",  "confidence": 0.8238858580589294 }

Then I updated rasa to 1.3.0, and retrain the nlu model and test it with the same word. But i got a really low confidence, like 0.51.  

According to https://rasa.com/docs/rasa/1.3.1/changelog/#:
- added character-level CountVectorsFeaturizer with empirically found parameters into the  supervised_embeddings NLU pipeline template.

So i did a little modification to the config.yml, i added following and retraint nlu model and i got the good intent confidence.
```
-  name: "CountVectorsFeaturizer"
   analyzer: "char_wb"
   min_ngram: 1
   max_ngram: 4
```
My question is:  does it make sense?  Is it normal?  What are those parameters for?

Thanks a lot!

**Comment by akelad** [comment]
i'm not sure the change in confidence has much to do with the fact that you upgraded versions. confidence can vary from training to training.

That being said, changing the config to that is definitely recommended - we found it improves intent classification a lot in general. The parameters determine what hte maximum and minimum lengths of the ngram should be. 

You're welcome to open a PR to update the config to include this :)

**Comment by MingL0L** [comment]
i'm not sure the change in confidence has much to do with the fact that you upgraded versions. confidence can vary from training to training.
>> To be clear, i did six training, before every training the only thing i changed is the version of Rasa OK? Here are different results when i text 'how old are you' by nlu shell.
      rasa 1.0.9    intent confidence:  0.91
      rasa 1.2.5    intent confidence:  > 0.8
      rasa 1.2.8    intent confidence:  > 0.8
      rasa 1.2.9    intent confidence:  > 0.8
      rasa 1.3.0    intent confidence:  < 0.6
      rasa 1.3.9    intent confidence:  < 0.6

BTW, you can easily reproduce it.  Only 3 steps:
1. pip install rasa==1.3.0
2  rasa shell nlu
3. "how old are you"
Why could not just test it and think about it....

**Comment by akelad** [comment]
there is no need to be hostile. For the record, trained with 1.3.9:
![image](https://user-images.githubusercontent.com/32450038/67229375-7a15af00-f43b-11e9-8b94-79fd90870009.png)

![image](https://user-images.githubusercontent.com/32450038/67229352-6c602980-f43b-11e9-9712-61123c2f58e0.png)


As I said, it varies from training to training
