### ISSUE TITLE
Test that the updated events list works 

### ISSUE THREAD

**Issue by eliseboyd** [RasaHQ/rasa-demo#347]
@akelad We made a change to the events list on this page: https://rasa.com/community/join/ and it now automatically pulls in the events from Airtable, which should help with keeping the list up to date 👌 

The generated HTML is effectively the same as before, so it _shouldn't_ break anything - you'll just need to check it's still rendering ok.

```<ul id="events-list">
<li>Paris<!-- -->, <a href="https://www.meetup.com/Rasa-Community-Paris/events/262844230/" rel="noopener noreferrer">Choisir sa solution de bot: technologies et benchmarks</a>, <!-- -->13 November, 2019</li>
<li>Paris<!-- -->, <a href="https://www.meetup.com/Rasa-Community-Paris/events/262844302/" rel="noopener noreferrer">Le design conversationnel</a>, <!-- -->11 December, 2019</li>
<li>Paris<!-- -->, <a href="https://www.meetup.com/Rasa-Community-Paris/events/262844380/" rel="noopener noreferrer">Atelier installation et utilisation de Rasa et Rasa X</a>, <!-- -->15 January, 2020</li></ul>```

**Comment by erohmensing** [comment]
I think it does break stuff unfortunately: 
```
2019-11-18 13:12:25 WARNING  demo.community_events  - Error when trying to parse event details from html.
2019-11-18 13:12:25 WARNING  demo.community_events  - Error when trying to parse event details from html.
2019-11-18 13:12:25 WARNING  demo.community_events  - Error when trying to parse event details from html.
```

**Comment by maggo** [comment]
Hey, the new event list has an added comma in the date so the check here https://github.com/RasaHQ/rasa-demo/blob/2364e07cd6f331524ab6f12308317e099e4821c8/demo/community_events.py#L30 is failing because the parts are always at least 4. 

We also have an optional ending date for events now, so the parsing logic needs to be updated to account for that.

Here's the react code: 
```jsx
<li>
  {city}, <Link to={link}>{name}</Link>,{' '}
  {!!rawEndDate && rawEndDate > rawDate
    ? `${new Date(rawDate).getDate()} – ${endDate}`
    : date}
</li>
```
