### ISSUE TITLE
Docker compose and custom actions don't work

### ISSUE THREAD

**Issue by ideivitcom** [RasaHQ/rasa-demo#350]
Hi. 
I can't get the docker-compose example to work with custom functions.
I put the message in the forum but I didn't get a reply.
https://forum.rasa.com/t/example-for-custom-action-docker-compose-not-working/21165

**Comment by ideivitcom** [comment]
Why the issue is closed without any response?

**Comment by akelad** [comment]
Because it's already on the forum and someone has gotten back to you there
