### ISSUE TITLE
Setup CI/CD Pipeline

### ISSUE THREAD

**Issue by btotharye** [RasaHQ/rasa-demo#352]
Setup a CI/CD Pipeline example for Sara showing how to connect to Travis, etc and run tests, update the model and bot, etc.

More information to go here later as we discuss it more. cc @akelad

**Comment by erohmensing** [comment]
There's already some cool stuff on carbon bot to branch off of, e.g. their script to post NLU results on every PR

**Comment by akelad** [comment]
yeah the idea was to start off of that :)

**Comment by akelad** [comment]
@btotharye how come you moved this back to backlog?

**Comment by btotharye** [comment]
just because this week I'm pretty busy and don't think I'll get to it this week, wasn't planned for this week or just eventually getting to it?  Sorry if I was confused.

**Comment by akelad** [comment]
it was planned for this week, that's why it's in "planned" - we talked about it during user success checkin

**Comment by akelad** [comment]
Alis helm updates won't be ready until the end of this week, so we can't work on it until then

**Comment by btotharye** [comment]
@akelad do you think for this issue to be resolved the last part is just setting up Sara on k8s with helm for the deployment stuff or any opinions on that now that we have the CI pipelines done.

**Comment by akelad** [comment]
are they merged yet? And yeah we should def set Sara up on k8s with helm. should be doable now that our helm charts are updated

**Comment by btotharye** [comment]
Yep we are not using travis anymore and are using github actions for the CI and the image deploy atm.

**Comment by btotharye** [comment]
ok I'm gonna spend some time today working on getting Sara up and running via helm on k8s in gcloud @akelad

**Comment by erohmensing** [comment]
@akelad do you think we should move this one to done and create a new issue for putting sara on K8s? Or unassign and move back to the backlog?

**Comment by akelad** [comment]
Yes please, let's close it and create a new one.

**Comment by erohmensing** [comment]
k8s deployment: https://github.com/RasaHQ/rasa-demo/issues/469
