### ISSUE TITLE
synonym of "both" is inconsistent

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#356]
I got a warning while training:
/Users/akela/miniconda3/envs/rasa/lib/python3.7/site-packages/rasa/nlu/training_data/util.py:24: UserWarning: Found inconsistent entity synonyms while reading markdown, overwriting both->stack with both->all during merge.
  f"Found inconsistent entity synonyms while {context_str}, "

We need to check in the code if we want it to be "all" or "stack"

**Comment by melindaloubser1** [comment]
which branch was this on? Not seeing this on master

**Comment by akelad** [comment]
well, in that case yay let's close it
