### ISSUE TITLE
"Rasa Open Source" name changes

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-demo#360]
Based on [this](https://website-demo.rasa.com/conversations/61bd24cad31c442994e252829ba3eecf) sara conversation, open source faq needs to be adjusted now that Rasa is called Rasa Open Source (prevents response to utter_ask_which_product from moving forward)

**Comment by akelad** [comment]
@rgstephens don't forget to add these to the "User success" board in future :)
