### ISSUE TITLE
install_rasa needs more examples

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-demo#362]
[This](https://website-demo.rasa.com/conversations/25d32983b0f349fda41eb3f15a1230c7) sara user asked `how to deploy you in local ?`. Our existing `install_rasa` intent does not include the word `deploy`.

We also don't have any Sara content that addresses local vs. server deployment.

There's also [this](https://website-demo.rasa.com/conversations/80ae8955140042dc8198ffa81b2a1c90) `How to build microservices` question we could throw into deployment.

**Comment by akelad** [comment]
@rgstephens can you separate that into two different issues? one about adding more NLU examples to install_rasa, and then an enhancement suggestion?
