### ISSUE TITLE
What are stories?

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-demo#368]
From [this](https://website-demo.rasa.com/conversations/32fbae6728454d34ba49149d5465071e) sara conversation. Don't see any intents along the lines of `what are stories?`

**Comment by akelad** [comment]
Do you think that would go under the new skill we're planning on adding? So suggesting forum posts, or first searching the docs for it

**Comment by rgstephens** [comment]
I was thinking this would both point to and quote the [Stories](https://rasa.com/docs/rasa/core/stories/) page in the docs. That page answers the question "What makes up a story?" at the beginning.

**Comment by akelad** [comment]
but so that's something we'd do with #355 right?

**Comment by erohmensing** [comment]
I personally don't think sara should be quoting stuff for technical questions, just pointing them to the right page
