### ISSUE TITLE
Review assigned conversations

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#378]
https://docs.google.com/spreadsheets/d/10yB8Yu5n84LRmkk-AZGEr5bhL7eqg1Zjej_07EA-FbE/edit#gid=0

**Comment by rgstephens** [comment]
I completed my set of conversations

**Comment by btotharye** [comment]
Just completed all of mine and left notes in the excel doc on the few I didn't and why.  Seems like users just left the convo not sure we need issues for those.

**Comment by ArjaanBuijk** [comment]
Also finished revieweing the ones assigned to me and created issues with links added to doc.
