### ISSUE TITLE
I have never programmed before

### ISSUE THREAD

**Issue by btotharye** [RasaHQ/rasa-demo#382]
From [This](https://website-demo.rasa.com/conversations/183289fc3458417787ce8a44f57537b2/1574734237.3510447) conversation we need to incorporate a story to be able to answer the following flow:

```
* get_started_step1
    - action_greet_user
    - slot{"shown_privacy":true}
    - slot{"step":"1"}
* technical_question
```

**Comment by ArjaanBuijk** [comment]
There are a lot of questions from users about:

-  the need for programming
- what programming language to use
- what programming language rasa is written in 

These can all be captured by a new intent `ask_is_programming_required`, with a response that explains that rasa is written in Python,  that you do not need to program yourself to define a bot, but that you can program custom actions. And explain that a python based SDK is provided for this.
