### ISSUE TITLE
Enhancement to `utter_ask_ready_to_build` for confirmation

### ISSUE THREAD

**Issue by btotharye** [RasaHQ/rasa-demo#385]
According to [This](https://website-demo.rasa.com/conversations/50976670513f48ea8d08a82b491eb519) conversation it appears it would be good to have a follow up here since we are asking them a question.  Our story training uses affirm/deny so we might need to add this phrase he asked in a way to these or different intents

This is our current story https://github.com/RasaHQ/rasa-demo/blob/master/data/core/step2_rasa_init.md#problems-installing that handles this

**Comment by akelad** [comment]
@btotharye that doesn't link to a timestamp, which part is the issue?

**Comment by btotharye** [comment]
[This](https://website-demo.rasa.com/conversations/50976670513f48ea8d08a82b491eb519/1574402575.3758225) one sorry that should work now I believe.

**Comment by akelad** [comment]
what do you mean? you can link to it: https://website-demo.rasa.com/conversations/50976670513f48ea8d08a82b491eb519/1574402575.3758225

I agree this should be changed though, should probably say something like "Did you manage to successfully install?"
