### ISSUE TITLE
How to use pi

### ISSUE THREAD

**Issue by btotharye** [RasaHQ/rasa-demo#387]
According to [This](https://website-demo.rasa.com/conversations/50976670513f48ea8d08a82b491eb519) conversation we need to work on the flow for `how to use pi` and variations if we want to include anything or otherwise move it to out of scope.  Part of this might be the flow the user was in that caused it.

**Comment by btotharye** [comment]
Could be handled in #355 but we don't have docs for this yet.  So leaving this one open for now.

**Comment by akelad** [comment]
this is about our api, so we can close
