### ISSUE TITLE
Question about pipelines

### ISSUE THREAD

**Issue by btotharye** [RasaHQ/rasa-demo#394]
From [This](https://website-demo.rasa.com/conversations/cfdb69701ce343c88dd88b2cbe60465c) conversation need to investigate why this didn't trigger the pipeline response flow and if that is the proper flow for this type of question.

Labelling bug as it may be a potential bug in the current setup.

**Comment by btotharye** [comment]
closing as duplicate of #355

**Comment by akelad** [comment]
this seems to be an issue with our flow, not a technical question
