### ISSUE TITLE
Does not understand: "how to load trained rasa model"

### ISSUE THREAD

**Issue by ArjaanBuijk** [RasaHQ/rasa-demo#412]
[Reference Conversation](https://website-demo.rasa.com/conversations/00140b046bc945f384c401c808d35520/1575367108.01136)

Valid question that must be recognized & answered

**Comment by ArjaanBuijk** [comment]
Maybe add as test case to https://github.com/RasaHQ/rasa-demo/issues/355 ?

**Comment by akelad** [comment]
@ArjaanBuijk i think the real issue here is that it doesn't respond to the technical question as it should, so it's about adding a story to handle that. The technical questions being answered more precisely is covered by #355

**Comment by ArjaanBuijk** [comment]
I verified it after latest updates with doc search and stories added with that. The conversation of this issue is now perfectly handled, without having to add anything else.
