### ISSUE TITLE
rasa page

### ISSUE THREAD

**Issue by nicolasfarina** [RasaHQ/rasa-demo#462]
How did your put this message on the rasa page?

![imagen](https://user-images.githubusercontent.com/52745496/73681756-cc52a700-469d-11ea-82d3-c73f6093e6cf.png)

**Comment by erohmensing** [comment]
Hi @nicolasfarina, are you talking about expanding the widget to have that message? A front-end coder did that for us, it's not handled out of the box AFAIK.

**Comment by nicolasfarina** [comment]
yes , thank you for the answer .

**Comment by erohmensing** [comment]
No prob :)
