### ISSUE TITLE
Docker Access Issue

### ISSUE THREAD

**Issue by govindshukl** [RasaHQ/rasa-demo#465]
![image](https://user-images.githubusercontent.com/6189929/74717057-c1247d00-5240-11ea-83b2-b98230e96efa.png)

during the execution of docker, get the enclosed issue, please advise.

**Comment by akelad** [comment]
hi, this is nothing to do with our images specifically, but rather authentication to docker hub. https://stackoverflow.com/questions/36663742/docker-unauthorized-authentication-required-upon-push-with-successful-login
