### ISSUE TITLE
Handle questions about how to use rasa x

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa-demo#472]
Question "how to use rasa x" recognized as `ask_faq_rasax` but answer is still about what rasa X is in general.

**Comment by akelad** [comment]
don't forget to put these issues in the user success board please ;)

**Comment by melindaloubser1** [comment]
ope sorry will do

**Comment by melindaloubser1** [comment]
@akelad was looking into this and discovered that the tutorial intents (`ask_faq_tutorialscore`,`ask_faq_tutorialsnlu`,`ask_faq_tutorials`) already overlap a lot resulting in the fallback policy kicking in most of the time; adding another `ask_faq_tutorials_x` (for which there is already a response - not sure why it's not in any stories?) only makes it worse. Seems like a good place to merge intents and split on `product` entity, but since the `faq` intents are handled by a custom action the tutorial qs would then have to be handled separately from the other faqs.

It would make sense to use a retrieval action here but since it seems we're still blocked on using the ResponseSelector (https://github.com/RasaHQ/rasa-demo/issues/344) I don't know if it makes sense to change this first?

**Comment by akelad** [comment]
Yep we're blocked by not using the ResponseSelector, which is blocked by the issue with the fallback action which I assigned you to

**Comment by melindaloubser1** [comment]
Ok cool then I'll leave this alone till that's sorted out

**Comment by melindaloubser1** [comment]
resolved by https://github.com/RasaHQ/rasa-demo/pull/483
