### ISSUE TITLE
learn more about 'rasa open source' leads to `ask_faq_opensource_cost`

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#481]
see http://website-demo.rasa.com/conversations/ef8c2fa8da2f470a8a67d4a3f7ab0444/1585325487.726087

and the slack thread here: https://rasa-hq.slack.com/archives/C4Q4X95M4/p1585309557028800

**Comment by akelad** [comment]
@melindaloubser1 do you have time to work on this? I think it should be a quick fix

**Comment by melindaloubser1** [comment]
yes I should be able to get to it this week
