### ISSUE TITLE
Investigate removing stop words from search queries

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#485]
For example, if the user asks `how to install rasa on docker-compose`:
![image](https://user-images.githubusercontent.com/22333512/79869158-49f69b00-83e1-11ea-9a0d-547f9752509b.png)

versus `install rasa docker-compose`:
![image](https://user-images.githubusercontent.com/22333512/79869450-aa85d800-83e1-11ea-8f9c-4995d1556ad1.png)

I think we should take ~10 examples each of tagged helpful/unhelpful docs and check to see if stripping stopwords would give more useful (judged by us) results or not make the good results any worse

**Comment by melindaloubser1** [comment]
@akelad Used spacy stopwords to check this out - based on this, it's somewhat better with stopwords removed. It's also clear that the changelogs aren't helping the search results. https://docs.google.com/spreadsheets/d/1WP_jxUtZ9VOJDlT9iD1vASI1CJ0Lug0ij4F1ORJYDAU/edit?usp=sharing

**Comment by melindaloubser1** [comment]
I used this script for it so we could try it with other/more stopwords too

**Comment by erohmensing** [comment]
@melindaloubser1 is "found help" coming from the feedback that the user gave or from you? 
Shall we try removing any changelog entries from the list before outputting the top 2 results?

**Comment by melindaloubser1** [comment]
If you expand the column, there's a "User found helpful?" column and a "New Results more helpful?" column. FIrst comes from auto tagging, second is my vote.  
I think that's worth trying, will post new results

**Comment by melindaloubser1** [comment]
@erohmensing added a column with changelog entries removed. Seems worth it and pretty low effort.

**Comment by erohmensing** [comment]
Cool, your decision led to few `no`s, so I think removing stopwords makes sense. From a look at the first page removing changelogs, definitely looks like there's some in there that have better results without it. I say we go for it 💯

**Comment by melindaloubser1** [comment]
Cool, I'll create an issue for implementing it

**Comment by melindaloubser1** [comment]
I think it could probably be improved by adding to the stopwords list - wdyt?

**Comment by erohmensing** [comment]
Yes good point, some ones i see in the doc that might be worth removing:
```
does
do
need
want
i
help
what
file(?)
can
could
may
was
wasn't
is
isn't
know
how
```
I think it makes sense to remove them for the docs search, but not the forum search, since users commonly create issues with these words (but maybe removing them would help match the relevant words better? idk, out of scope)

also i think it makes sense to strip any punctuation, don't know if question marks are doing us any favors either

**Comment by melindaloubser1** [comment]
agreed on removing from docs search only & stripping punctuation

**Comment by akelad** [comment]
can we close this then?

**Comment by erohmensing** [comment]
Yep I'd say so, all about that #progress

**Comment by melindaloubser1** [comment]
@erohmensing sorry to bring up a closed issue - shoulda thought of this, but looks like those additional ones are accounted for if the text is tokenized first. Should we use spacy to tokenize the search text first? I guess I could try that out and see
