### ISSUE TITLE
Trying to run Sara

### ISSUE THREAD

**Issue by Outstep** [RasaHQ/rasa-demo#500]
Hello,

I have just come across your Sara demo while reading up on Rasa and what it can do, but when I tried to install it on my Debian 9 system, I get an error with pip:

asa-demo$ pip install -r requirements.txt
Collecting rasa[convert]~=1.10.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement rasa[convert]~=1.10.0 (from -r requirements.txt (line 1)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.1.1, 0.2.0a2, 0.2.0a3, 0.14.0a5, 0.14.0a6, 0.14.0a7, 0.14.0a8, 0.14.0a9, 0.15.0a6, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0rc5, 1.0.0rc6, 1.0.0rc7, 1.0.0rc8, 1.0.0rc9, 1.0.0rc10, 1.0.0rc11, 1.0.0rc12, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.2.0a2, 1.2.0a3, 1.2.0a4, 1.2.0a5, 1.2.0a6, 1.2.0a7, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.11, 1.2.12, 1.3.0a1, 1.3.0a2, 1.3.0, 1.3.1a1, 1.3.1a3, 1.3.1a4, 1.3.1a5, 1.3.1a8, 1.3.1a10, 1.3.1a11, 1.3.1a12, 1.3.1a14, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10)
No matching distribution found for rasa[convert]~=1.10.0 (from -r requirements.txt (line 1))

Is there a solution to this?

Also, I noticed that  there is a Docker file that could also be used. Is that to Sara or Duckling?

If Sara, then what is the CLI invocation for it?

Thanks in advance

**Comment by akelad** [comment]
Which python version do you have installed? It needs to be 3.6 or higher

**Comment by akelad** [comment]
The Dockerfile is just to run the action server of Sara

**Comment by lonnietc** [comment]
I am on a Debian 9 system.

for Python3 -V I get 3.7.3, but now in using 

cd rasa-demo
pip3 install -r requirements.txt

I get a tensorflow error:
.
.
.
Collecting fbmessenger<6.1.0,>=6.0.0 (from rasa[convert]~=1.10.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bd/e9/646684226176782b9e3b7dd5b35d7ecfd1d13cba24ad2e33255079921aab/fbmessenger-6.0.0-py2.py3-none-any.whl
Collecting tensorflow<2.2,>=2.1 (from rasa[convert]~=1.10.0->-r requirements.txt (line 1))
  Could not find a version that satisfies the requirement tensorflow<2.2,>=2.1 (from rasa[convert]~=1.10.0->-r requirements.txt (line 1)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow<2.2,>=2.1 (from rasa[convert]~=1.10.0->-r requirements.txt (line 1))

**Comment by akelad** [comment]
Hm, I would suggest using a virtual environment if you're not doing that already. As described in the rasa documentation: https://rasa.com/docs/rasa/user-guide/installation/

**Comment by lonnietc** [comment]
Thanks again.

I'll look into it more.

**Comment by akelad** [comment]
I will close this for now, if you have more issues with installing Rasa, please post in our community [forum](https://forum.rasa.com)
