### ISSUE TITLE
Handle "why rasa"

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#508]
Look for user inputs like 
- why should i use rasa
- why rasa
- why should i use rasa over others”
- how does rasa compare to dialogflow

etc. 

Some of the content could come from a page like [this](https://rasa.com/docs/rasa/migrate-from/ibm-watson-to-rasa/) (i.e. why rasa over cloud-based tools)

**Comment by melindaloubser1** [comment]
e.g. https://website-demo.rasa.com/conversations/45adf51a890d41b7a58f538feb73957d/1588672181.33693
