### ISSUE TITLE
"rasax" as answer to "which product do you want to know more about" doesn't work

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#520]
http://website-demo.rasa.com/conversations/cefef474c37649bcada98bc1c07b2187/1589230149.4084873

I think this is because of intent detection instead of entity extraction 🤔

**Comment by melindaloubser1** [comment]
sounds like the same issue as when it was looping in the onboarding flow because of extracting detecting the open source intent, not the "getting started" intent.

**Comment by melindaloubser1** [comment]
https://github.com/RasaHQ/rasa-demo/pull/482
