### ISSUE TITLE
ERROR: No matching distribution found for tensorflow_text==2.1.0rc0

### ISSUE THREAD

**Issue by dhapolapankaj** [RasaHQ/rasa-demo#548]
Team,

I tried below command
`pip install -r requirements.txt`

Got below error message after installing lot of other libraries

![image](https://user-images.githubusercontent.com/29034223/84906331-68220400-b0cf-11ea-9b2a-2a1b989172b7.png)

I did some research and it looks like this library is not available for windows.

ERROR: No matching distribution found for tensorflow-text==2.2.1

[https://github.com/tensorflow/text/issues/44](https://github.com/tensorflow/text/issues/44)

Can you guys please look for alternative?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
@dhapolapankaj Thanks for your feedback! Unfortunately we won't get rid of this dependency in the close / mid term future. However, what you can do is to choose different NLU components which don't require this (e.g. just by using the `SpacyFeaturizer` instead of the `ConveRTFeaturizer`
