### ISSUE TITLE
How to fix the input size of NLU pipeline?

### ISSUE THREAD

**Issue by sainimohit23** [RasaHQ/rasa-demo#549]
I have a few very long training examples in ‘nlu.md’. When I train my NLU pipeline, it exhausts all the system resources and crashes my system. How to fix the input length in the NLU without worrying about the training data examples?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Hi @sainimohit23 , the right place to ask questions like this is the [forum](https://forum.rasa.com/); I'm closing this as a question since it's not related to this repo.
