### ISSUE TITLE
What does this trigger_rephrase mean？

### ISSUE THREAD

**Issue by YYGe01** [RasaHQ/rasa-demo#551]
Hello,
In the `config.yml `file, 
`deny_suggestion_intent_name: "trigger_rephrase"`
What does this `trigger_rephrase` mean,Is it related to `utter_ask_rephrase` in the `domain.yml` file?

I am a beginner in rasa, is there any documentation about trigger to learn?Thank you

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Hi, this is about the `TwoStageFallbackPolicy` and the you can learn more about this [here](https://rasa.com/docs/rasa/core/fallback-actions/#two-stage-fallback-policy), see this section:
> If the user denies, the original intent is classified as the specified deny_suggestion_intent_name, and an ultimate fallback action fallback_nlu_action_name is triggered (e.g. a handoff to a human).

I'm closing this issue as a question, the forum is a good place to go with questions in the future =)
