### ISSUE TITLE
its thowing issue for tensorflow_text is Could not find a version that satisfies the requirement tensorflow_text==2.1.0rc0.

### ISSUE THREAD

**Issue by kiran79k** [RasaHQ/rasa-demo#561]
ERROR: Could not find a version that satisfies the requirement tensorflow_text==2.1.0rc0; extra == "convert" or extra == "full" (from rasa[convert]~=1.10.0->-r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow_text==2.1.0rc0; extra == "convert" or extra == "full" (from rasa[convert]~=1.10.0->-r requirements.txt (line 1))

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
I wouldn't mind helping you here, but it would help if I knew what actions you took that led you to this error message.

**Comment by mlacayoemery** [comment]
Try updating pip and then installing tensorflow 2.1.1

`pip3 install --upgrade pip`
`pip3 install tensorflow==2.1.1`

That did the trick for me.

**Comment by koaning** [comment]
I'll close the issue then. Happy to hear you've got it working :)
