### ISSUE TITLE
Why is the same story written 5 times? How different is one from another?

### ISSUE THREAD

**Issue by Akhil-YS** [RasaHQ/rasa-demo#585]
I have been studying the "explain" intent and found the same story is written 5 times. Why so? How are they different from each other?

https://github.com/RasaHQ/rasa-demo/blob/master/data/core/faqs.md#faq---tell-more-about-rasa-x-ee

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment]
Closing this as it's been fixed recently 🙂
