### ISSUE TITLE
train too slowly

### ISSUE THREAD

**Issue by xiaolinpeter** [RasaHQ/rasa-demo#600]
hi, I spend too much time in training model, how to train model in GPU?

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
Please ask this question in the [forum](https://forum.rasa.com).

I can also suggest you [this](https://rasa.com/docs/rasa/tuning-your-model#configuring-tensorflow) docs page. Alternatively you can always lower the number of training epochs in the model configuration.
