### ISSUE TITLE
need help in deploying bot in Azure Web App

### ISSUE THREAD

**Issue by karthik291994** [RasaHQ/rasa-demo#625]
Hi,
I am try to deploy the bot Azure with Docker container. trying run in local but its running only actions server only.
 docker file:-
FROM rasa/rasa:2.4.0-full
FROM rasa/rasa-sdk:2.0.0

Use subdirectory as working directory
WORKDIR /app

 Copy actions requirements
COPY actions/requirements-actions.txt ./

# Change to root user to install dependencies
USER root

# Install extra requirements for actions code
RUN pip install -r requirements-actions.txt

 Copy actions code to working directory
COPY ./actions /app/actions
 Install modules from setup.py
COPY setup.py /app
RUN pip install . --no-cache-dir

 Download spacy language data
RUN python -m spacy download en_core_web_md
RUN python -m spacy link en_core_web_md en

 Don't use root user to run code
USER 1001
VOLUME /app
VOLUME /app/data
VOLUME /app/models

CMD ["run","-m","/app/models","--enable-api","--cors","*","--debug" ]

actions/docker file:- 
FROM rasa/rasa-sdk:2.0.0
ADD . /app/actions
ENTRYPOINT []
CMD python3 -m rasa-sdk --actions actions -p $PORT

docker build successful.
 

please let me where i am doing wrong

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
Please post questions in our [forum](https://forum.rasa.com) and you can ask for my help there as `stephens`. I will close this issue. In the forum post let me know the following:

- Are you using our [docker-compose install](https://rasa.com/docs/rasa-x/installation-and-setup/install/docker-compose/)
- What does the `docker-compose ps` command show
