### ISSUE TITLE
I need help regarding seeting up real estate bot please help me

### ISSUE THREAD

**Issue by vivek22122014** [RasaHQ/rasa-demo#626]
I treid but I'm getting this error
ActionNotFoundException: Cannot access action 'form{"name":"sell_form"}', as that name is not a registered action for this domain. Available actions are:
         - action_listen
         - action_restart
         - action_session_start
         - action_default_fallback
         - action_deactivate_loop
         - action_revert_fallback_events
         - action_default_ask_affirmation
         - action_default_ask_rephrase
         - action_two_stage_fallback
         - action_back
         - ...
         - utter_smalltalk_agent_acquaintance
         - utter_smalltalk_agent_age
         - utter_iamabot
         - utter_smalltalk_agent_annoying
         - utter_smalltalk_agent_answer_my_question
         - utter_smalltalk_agent_bad
         - utter_smalltalk_agent_be_clever
         - utter_smalltalk_agent_beautiful
         - utter_smalltalk_agent_birth_date
         - utter_smalltalk_agent_boring
         - utter_smalltalk_agent_boss
         - utter_smalltalk_agent_busy
         - utter_smalltalk_agent_chatbot
         - utter_smalltalk_agent_clever
         - utter_smalltalk_agent_crazy
         - utter_smalltalk_agent_fired
         - utter_smalltalk_agent_funny
         - utter_smalltalk_agent_good
         - utter_smalltalk_agent_happy
         - utter_smalltalk_agent_hungry
         - utter_smalltalk_agent_marry_user
         - utter_smalltalk_agent_my_friend
         - utter_smalltalk_agent_occupation
         - utter_smalltalk_agent_origin
         - utter_smalltalk_agent_ready
         - utter_smalltalk_agent_real
         - utter_smalltalk_agent_residence
         - utter_smalltalk_agent_right
         - utter_smalltalk_confirmation_yes
         - utter_smalltalk_agent_sure
         - utter_smalltalk_agent_talk_to_me
         - utter_smalltalk_agent_there
         - utter_smalltalk_appraisal_bad
         - utter_smalltalk_appraisal_good
         - utter_smalltalk_appraisal_no_problem
         - utter_smalltalk_appraisal_thank_you
         - utter_smalltalk_appraisal_welcome
         - utter_smalltalk_appraisal_well_done
         - utter_smalltalk_confirmation_cancel
         - utter_smalltalk_confirmation_no
         - utter_smalltalk_dialog_hold_on
         - utter_smalltalk_dialog_sorry
         - utter_smalltalk_dialog_what_do_you_mean
         - utter_smalltalk_dialog_wrong
         - utter_smalltalk_emotions_ha_ha
         - utter_smalltalk_emotions_wow
         - utter_smalltalk_greetings_bye
         - utter_smalltalk_greetings_goodevening
         - utter_smalltalk_greetings_goodmorning
         - utter_smalltalk_greetings_goodnight
         - utter_smalltalk_greetings_hello
         - utter_smalltalk_greetings_how_are_you
         - utter_smalltalk_greetings_nice_to_meet_you
         - utter_smalltalk_greetings_nice_to_see_you
         - utter_smalltalk_greetings_nice_to_talk_to_you
         - utter_smalltalk_greetings_whatsup
         - utter_smalltalk_user_angry
         - utter_smalltalk_user_excited
         - utter_smalltalk_user_has_birthday
         - utter_smalltalk_user_needs_advice
         - utter_smalltalk_user_tired
         - utter_smalltalk_user_waits
         - utter_smalltalk_user_will_be_back
         - utter_greet
         - utter_goodbye
         - utter_submit_buy
         - utter_submit_sell
         - utter_ask_address
         - utter_ask_bathrooms
         - utter_ask_bedrooms
         - utter_ask_city
         - utter_ask_cost
         - utter_ask_country
         - utter_ask_email
         - utter_ask_months
         - utter_ask_phone_number
         - utter_ask_property_type
         - utter_ask_time_to_sell
         - utter_ask_zipcode
         - utter_cheer_up
         - utter_did_that_help
         - utter_happy
         - buy_form
         - sell_form

I guess some error realted to forms, it'll be great help if anyone help me out I can share files via mail

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
