### ISSUE TITLE
rasa shell command opens rasa intecative why?  opens the detailed confidence information etc.

### ISSUE THREAD

**Issue by vivek22122014** [RasaHQ/rasa-demo#627]
Hello Every time I run “rasa shell” , it runs as if I type “rasa shell nlu” . I am trying to run “rasa shell” normally but it opens the detailed confidence information etc.

![Screenshot (278)](https://user-images.githubusercontent.com/58829538/113280927-92f9e380-9302-11eb-9bc8-83c3945d839f.png)
![Screenshot (277)](https://user-images.githubusercontent.com/58829538/113280838-78c00580-9302-11eb-8e48-16e325dbdae3.png)

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Closing this as it is a usage question; please post on the [Rasa forum](https://forum.rasa.com/) if you still need help
