### ISSUE TITLE
Every time I run “rasa shell” , it runs as if I type “rasa shell nlu” . I am trying to run “rasa shell” normally but it opens the detailed confidence information etc.

### ISSUE THREAD

**Issue by vivek22122014** [RasaHQ/rasa-demo#628]
Core training was skipped because no valid domain file was found. Only an NLU-model was created. Please specify a valid domain using the '--domain' argument or check if the provided domain file exists.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @samsucik will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment]
Hey @vivek22122014, it looks like no Rasa Core models are getting trained because you don't have a domain file. Is this intended?

**Comment by vivek22122014** [comment]
I do have domain  file

**Comment by vivek22122014** [comment]
> 
> 
> Hey @vivek22122014, it looks like no Rasa Core models are getting trained because you don't have a domain file. Is this intended?

I have domain file @samsucik

**Comment by vivek22122014** [comment]
![Screenshot (279)](https://user-images.githubusercontent.com/58829538/113308069-6d310680-9323-11eb-83d7-e3ebf099ec29.png)

**Comment by samsucik** [comment]
Hmmm, that's interesting. Are you specifying the domain with the `--domain` argument? Also, what version of Rasa and Python are you using?

**Comment by vivek22122014** [comment]
Rasa Version     : 2.4.0
Rasa SDK Version : 2.4.0
Rasa X Version   : 0.37.1
Python Version   : 3.7.8
Operating System : Windows-10-10.0.19041-SP0

**Comment by samsucik** [comment]
@vivek22122014 thanks; can you also respond to my other question? Perhaps specifying the domain explicitly can help us move forward.

**Comment by melindaloubser1** [comment]
Closing this as it is a usage question; please post on [the Rasa forum](https://forum.rasa.com/) if you still need help
