### ISSUE TITLE
Try to deploy the rasa bot in Azure web app service

### ISSUE THREAD

**Issue by karthik291994** [RasaHQ/rasa-demo#629]
Hi I am try to deploy the bot in Azure web app. i have done with docker-compose file it is working fine i am getting Hello rasa version with https://rasademochatbot9618.azurewebsites.net/ but here the problem is not able to connect in Front if i am keeping this URL in my website not able to see the bot. can you tell me where i am doing wrong in local it is working fine 

![image](https://user-images.githubusercontent.com/69871421/113579934-995dc780-9642-11eb-9bf1-cf0386cd5015.png)
 Docker-compose file:

version: '3.0'
services:
  mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: chatbot_lanconic
        MONGO_INITDB_ROOT_PASSWORD: DzqlKqaON4HQQGKz
  mongo-express:  
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chatbot_lanconic
      ME_CONFIG_MONGODB_ADMINPASSWORD: DzqlKqaON4HQQGKz
  rasa:
    container_name: rasa_server
    image: rasa/rasa:1.7.0
    build: 
      context: backend
    ports: 
      - "5005:5005"
  action_server:
    container_name: action_server
    image: rasa/rasa-sdk:1.7.0
    build: 
      context: actions
    volumes:
      - ./actions:/app/actions        
    ports:
      - "5055:5055"  

Docker file in backend folder:

# Pull SDK image as base image
FROM rasa/rasa:1.7.0-full

WORKDIR /app
COPY . /app
COPY ./data /app/data

CMD  ["run","-m","/app/models","--enable-api","--endpoints","endpoints.yml","--credentials","credentials.yml","--cors","*","--debug"]

Docker file in action folder:
FROM rasa/rasa-sdk:1.7.0

USER root 
RUN pip3 install pandas
RUN pip3 install datetime
RUN pip3 install requests

USER 1001

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @karthik291994, we keep github issues for enhancements and bug reports (things that require code changes to implement). Please ask your question in the [forum](forum.rasa.com) and we'll help you get down to the bottom of it.
