### ISSUE TITLE
Store collected data somewhere

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#7]
- [x] For the newsletter: send the email address to the mailchimp API or similar
- [x] For the sales stuff: store in a spreadsheet

**Comment by victorbai2** [comment]
@akelad  Hi akelad, can you please provide the documentation of how to get or generate a credential for gspread.
I do not know which key is for credential, so for simplicity, I directly used the json file with below code:
```
        scopes = [
            'https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive'
        ]
        self.credentials = ServiceAccountCredentials.from_json_keyfile_name(
            'credentials/Service_account_key.json',
            scopes=scopes
        )
```
But it shows that I still could not connect to the spreadsheet:
`Failed to create google spreadsheet connection. `
