### ISSUE TITLE
rasa init NO response

### ISSUE THREAD

**Issue by hjing100** [RasaHQ/rasa-demo#731]
python=3.9 
rasa=3.2.1
rasa init No response

**Comment by trammell** [comment]
Unable to reproduce, here's what I see (MacOS, Intel):

```console
mkdir foo
cd foo
python3.9 -m venv venv
source ./venv/bin/activate
pip install rasa==3.2.1 websockets==10.4
rasa init

...

>>> Welcome to Rasa!
```

My recommendation would be to use a more recent Rasa open source version, what's so special about v3.2.1?
