### ISSUE TITLE
Undefined utter template for /restart

### ISSUE THREAD

**Issue by AnilLG** [RasaHQ/rasa-demo#99]
![screenshot from 2018-08-13 18-16-46](https://user-images.githubusercontent.com/39720422/44081467-66970466-9fcc-11e8-80d4-27feaee6b04c.png)

**Comment by kappaganthusivaram** [comment]
I am also facing this issue. Could someone please help?

**Comment by akelad** [comment]
It's just not defined yet, you can continue chatting with the bot by typing "hi". We'll make sure to define an utterance for that ASAP

**Comment by akelad** [comment]
Fixed
